version: "3.0"

services:
    mongodb:
        image: mongo:4.0-xenial
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
